### ISSUE TITLE
drupal.org release?

### ISSUE THREAD

**Issue by nicrodgers** [dawehner/workbench_moderation_actions#2]
hi @dawehner, thanks for the module - really useful. Would you consider releasing it on drupal.org?

It seems to be stable, and would be good to have the benefit of d.o security coverage, composer support etc...

**Comment by dawehner** [comment]
If you want you can also just take it. I don't use it at the moment, so it
would be probably better in your hands.

Otherwise I will try to find the time somehow.

Nic Rodgers <notifications@github.com> schrieb am Fr., 30. Juni 2017 um
15:08 Uhr:

**Comment by nicrodgers** [comment]
I'd be happy to help out and take it on. I'll set up the project on d.o and will be sure to give you credit for the work to date.

**Comment by nicrodgers** [comment]
Let me know if there's an organisation I should credit on the module page.

**Comment by dawehner** [comment]
Feel free to credit chapter three.

Thank you for doing the work!

**Comment by nicrodgers** [comment]
Ok, I've set up a project on d.o:
https://www.drupal.org/project/workbench_moderation_actions

I've also created a request to get drupal security advisory coverage:
https://www.drupal.org/node/2891759

**Comment by dawehner** [comment]
Thank you a lot!

Nic Rodgers <notifications@github.com> schrieb am Mo., 10. Juli 2017 um
11:18 Uhr:
